- name: copy certificate
  become: yes
  become_method: sudo
  copy:
    src: "{{ ssl_certificate }}"
    dest: "/etc/ssl/certs/"

- name: copy certificate key
  become: yes
  become_method: sudo
  copy:
    src: "{{ ssl_certificate_key }}"
    dest: "/etc/ssl/private/"

- name: copy pod_nginx.conf into custom directory
  become: yes
  become_method: sudo
  template:
    src: "../templates/pod3_nginx_ssl.conf.j2"
    dest: "{{django_path}}/pod/custom/pod_nginx.conf"
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0744

- name: copy nginx.conf into /etc/nginx/ directory
  become: yes
  become_method: sudo
  template:
    src: "../templates/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"

- name : create link  into nginx directory
  become: yes
  become_method: sudo
  file:
   src: "{{django_path}}/pod/custom/pod_nginx.conf"
   dest: "/etc/nginx/sites-enabled/pod_nginx.conf"
   state: link

- name: create dir /etc/pki/tls/certs/
  become: yes
  become_method: sudo
  file:
    path: "/etc/pki/tls/certs"
    state: directory
    recurse: yes

- name: Generate dhparam file for Nginx
  become: yes
  become_method: sudo
  community.crypto.openssl_dhparam:
    path: /etc/pki/tls/certs/dhparam.pem
    size: 4096

- name: restart nginx en sudo
  become: yes
  become_method: sudo
  service:
    name: nginx
    state: restarted
    enabled: yes



